### PR TITLE
Make localdevstorage compatible with Python 3

### PR DESCRIPTION
**Pull request by anrie**
Hey Benjamin,

this PR should make localdevstorage compatible with Python 3.
So far I tested the HTTP backend  manually against Python 2.7 and Python 3.4.

Obviously tox and an extended testsuite would be nice, but I first wanted to check if you are interested in Python 3 compatibility.

### CODE REVIEW

**Comment by jonasvp** [comment]
Any way this could be merged? Would be very useful for us...

**Comment by piquadrat** [comment]
@anrie great, thanks. It's true that tests would be great. I don't really use this project myself anymore, hence the less-than-great (to say the least) maintainership

**Comment by beniwohli** [comment]
@anrie thanks again for your code and sorry for the taking so long to merge it in. I wrote a few tests and set up travis-ci to test it with Python 2.6/2.7 and 3.3/3.4

**Comment by anrie** [comment]
@piquadrat Just out of curiosity: Why aren't you using `localdevstorage` anymore? 
For me it's one of these small helper apps I stumbled accross and I really wouldn't want to miss.

Thanks that you took the time for a new release!

**Comment by beniwohli** [comment]
@anrie just a different job that doesn't involve any uploaded media at all :)

**Pull request merged**
